### ISSUE TITLE
Use grid 6 to make consistency instead of using 5 grid

### ISSUE THREAD

**Issue by ibigrock-ashish** [chandanvyas/960Grid#18]
<span class="grid_5">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
                </span>

**Comment by techsquad-chandanvyas** [comment]
Fixed
