### ISSUE TITLE
Errors in index.html

### ISSUE THREAD

**Issue by techsquad-ruchikatokish** [chandanvyas/960Grid#23]
Error: Element h1 not allowed as child of element span in this context. (Suppressing further errors from this subtree.)

    From line 15, column 17; to line 15, column 20

              <h1>960Gri

    Content model for element span:
        Phrasing content. 

    Error: Element ul not allowed as child of element span in this context. (Suppressing further errors from this subtree.)

    From line 19, column 17; to line 19, column 33

              <ul class="menu">↩     

    Contexts in which element ul may be used:
        Where flow content is expected. 
    Content model for element span:
        Phrasing content. 

    Error: Element div not allowed as child of element span in this context. (Suppressing further errors from this subtree.)

    From line 35, column 17; to line 35, column 35

              <div class="clear"></div>

    Contexts in which element div may be used:
        Where flow content is expected. 
        As a child of a dl element. 
    Content model for element span:
        Phrasing content. 

    Error: Element div not allowed as child of element span in this context. (Suppressing further errors from this subtree.)

    From line 41, column 17; to line 41, column 35

              <div class="clear"></div>

    Contexts in which element div may be used:
        Where flow content is expected. 
        As a child of a dl element. 
    Content model for element span:
        Phrasing content. 

    Error: Element div not allowed as child of element span in this context. (Suppressing further errors from this subtree.)

    From line 47, column 17; to line 47, column 35

              <div class="clear"></div>

    Contexts in which element div may be used:
        Where flow content is expected. 
        As a child of a dl element. 
    Content model for element span:
        Phrasing content. 

    Error: Element div not allowed as child of element span in this context. (Suppressing further errors from this subtree.)

    From line 54, column 21; to line 54, column 39

              <div class="clear"></div>

    Contexts in which element div may be used:
        Where flow content is expected. 
        As a child of a dl element. 
    Content model for element span:
        Phrasing content. 

    Error: Element div not allowed as child of element span in this context. (Suppressing further errors from this subtree.)

    From line 58, column 17; to line 58, column 41

              <div class="grid_6 row1">↩     

    Contexts in which element div may be used:
        Where flow content is expected. 
        As a child of a dl element. 
    Content model for element span:
        Phrasing content.

**Comment by techsquad-chandanvyas** [comment]
Fixed
