### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by techsquad-ruchikatokish** [chandanvyas/960Grid#25]
Please correct the folder structure.

**Comment by techsquad-chandanvyas** [comment]
What is the issue with folder structure??

**Comment by techsquad-ruchikatokish** [comment]
ionicons-2.0.1 folder contains ionicons-2.0.1 folder which inturn contains the required files/folders.
ionicons-2.0.1 -->> ionicons-2.0.1 -->> required files/folder
Ideally it should be  ionicons-2.0.1 -->> required files/folder

Further please check if this folder is required or not.

**Comment by techsquad-chandanvyas** [comment]
Fixed
